### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by ranjan-purbey** [tari01/caja-rename#1]
Is it possible to use a wildcard/regex to replace text in filename?

**Comment by tari01** [comment]
> Is it possible to use a wildcard/regex to replace text in filename?

Sorry for the delay. I made Caja Rename to be as easy to use as possible, so there is no regex on purpose. For situations when there is a need for some advanced tinkering, I would suggest _gprename_ or some other standalone tool.

**Comment by ranjan-purbey** [comment]
Thank you
