### ISSUE TITLE
How to bring up Caja Rename dialog

### ISSUE THREAD

**Issue by TheJags** [tari01/caja-rename#2]
I don't know what am I missing in here but I can't seem to find a way to bring up "Caja Rename dialog" in `Ubuntu MATE 20.10`

`Installed version: caja-rename 20.1.25~bzr37-1`

Here's a screenshot I found on `https://tari.in/www/software/caja-rename/`

![caja-rename](https://user-images.githubusercontent.com/47936415/114249952-bdf6ce00-99b9-11eb-8e63-b423ab6e0390.jpg)

Thanks alot in advance.

**Comment by tari01** [comment]
@TheJags 

Select multiple files/folders in Caja, right-click them and select the "Rename..." menu item.

**Comment by TheJags** [comment]
@tari01 Thanks for the quick reply.

As soon as I select 2 or more files, and right-click; `Rename` becomes unavailable.

Screenshot:

![caja-rename2](https://user-images.githubusercontent.com/47936415/114254359-7f1e4380-99cc-11eb-9412-a22c994321d5.jpg)

**Comment by TheJags** [comment]
Right after I posted the screenshot above, I noticed the **2nd** `Rename` at the bottom. It's working, and does bring up the caja-rename dialog.

Thanks alot :)

**Comment by tari01** [comment]
Hmm... It seems Caja has changed its behaviour. Back when I wrote the application the original "Rename" went away when there was no selection, so it was conveniently replaced by the other menu item. I will probably need to change the name to "Rename all..." or something similar.

Anyway, closing this issue. :)

**Comment by TheJags** [comment]
@tari01 yes, `Rename all...` would be great. Thank you.
