### ISSUE TITLE
caja-rename causes to caja-file-management-properties fill ~/.xsession-errors with python-related warnings

### ISSUE THREAD

**Issue by N0rbert** [tari01/caja-rename#6]
Steps to reproduce:
1. Install Ubuntu MATE 21.10 beta
2. Launch `caja-file-management-properties` from terminal

Expected results: terminal shows only three lines 

```
Initializing caja-wallpaper extension
Initializing caja-sendto extension
Initializing caja-open-terminal extension
```

Actual results: terminal shows many lines like shown below

```
(caja-file-management-properties:7372): Gtk-WARNING **: 21:22:42.535: Failed to set text from markup due to error parsing markup: Error on line 1 char 29: Invalid UTF-8 encoded text in name — not valid “Python: H3\x89c\u0005”
```

If user starts Caja and goes to Edit → Preferences and then to Extensions tab then `~/.xsession-errors` fills with above messages.

Downstream meta-bug - https://pad.lv/1945052 .

**Comment by tari01** [comment]
@N0rbert 

I'm a bit puzzled by this. I haven't changed anything in the caja-rename internals for quite some time. I have a feeling that this is coming from elsewhere (python-caja?). On my system, some Caja extensions are displayed twice while some are not in the list at all.

**Comment by N0rbert** [comment]
Thank you for reply! 
I'm puzzled too. Let's wait for comments on MATE python-caja issue.

**Comment by tari01** [comment]
@N0rbert 

I see there was some activity on https://github.com/mate-desktop/python-caja/issues/66. Does caja-rename work for you as expected?

**Comment by N0rbert** [comment]
Thanks! Yes, it works!
